In [1]:
import numpy as np
import torch

In [9]:
w = torch.tensor([0.2 , 0.66, 0.42],dtype=torch.float32)
c = torch.tensor([1, 2, 3],dtype=torch.float32)

In [10]:
torch.softmax(c, dim=0)

tensor([0.0900, 0.2447, 0.6652])

In [31]:
torch.nn.functional.log_softmax(c, dim=0)

tensor([-5.0550, -3.0550, -0.0550])

In [32]:
3*torch.softmax(w*torch.softmax(c))

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype, *, Tensor out)
 * (Tensor input, name dim, *, torch.dtype dtype)


In [2]:
cc = torch.tensor([1, 2, 3], dtype=torch.float32)

In [5]:
torch.nn.Softmax(dim=0)(cc)

tensor([0.0900, 0.2447, 0.6652])

In [11]:
def softmax(x):
    # 计算每行的最大值
    row_max = np.max(x)
    # 每行元素都需要减去对应的最大值，否则求exp(x)会溢出，导致inf情况
    x = x - row_max
    # 计算e的指数次幂
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp)
    s = x_exp / x_sum
    return s

In [12]:
softmax(np.array([1, 2, 3], dtype=np.float32))

array([0.09003057, 0.24472846, 0.66524094], dtype=float32)